db.courses.insert({'department': 'ENGR ', 'coursenumber': '101' , 'prerequisites': ['Intro Comp&Prog','|','|','ENGR 151','EECS 183']});
db.courses.insert({'department': 'EECS ', 'coursenumber': '183' , 'prerequisites': ['Elementary Programming Concepts','|','|','ENGR 101','ENGR 151']});
db.courses.insert({'department': 'EECS ', 'coursenumber': '203' , 'prerequisites': ['Discrete Mathematics','|','MATH 115','MATH 116','MATH 119','MATH 120','MATH 121','MATH 156','MATH 175','MATH 176','MATH 185','MATH 186','MATH 214','MATH 215','MATH 216','MATH 217','MATH 255','MATH 256','MATH 285','MATH 286','MATH 295','MATH 296','MATH 417','MATH 419']});
db.courses.insert({'department': 'EECS ', 'coursenumber': '270' , 'prerequisites': ['Introduction to Logic Design','|','EECS 183','ENGR 101']});
db.courses.insert({'department': 'EECS ', 'coursenumber': '280' , 'prerequisites': ['Programming and Introductory Data Structures','|','EECS 182','EECS 183','ENGR 101','ENGR 151']});
db.courses.insert({'department': 'EECS ', 'coursenumber': '281' , 'prerequisites': ['Data Structures and Algorithms','EECS 280','|','EECS 203','MATH 465','MATH 565']});
db.courses.insert({'department': 'EECS ', 'coursenumber': '370' , 'prerequisites': ['Introduction to Computer Organization','EECS 280','|','EECS 203','EECS 270','MATH 465','MATH 565']});
db.courses.insert({'department': 'EECS ', 'coursenumber': '373' , 'prerequisites': ['Design of Microprocessor Based Systems','EECS 270','EECS 370']});
db.courses.insert({'department': 'EECS ', 'coursenumber': '376' , 'prerequisites': ['Foundations of Computer Science','EECS 280','|','EECS 203','MATH 465','MATH 565']});
db.courses.insert({'department': 'EECS ', 'coursenumber': '381' , 'prerequisites': ['Object Orientated and Advanced Programming','EECS 281','EECS 370']});
db.courses.insert({'department': 'EECS ', 'coursenumber': '382' , 'prerequisites': ['Internet-scale Computing','|','EECS 281','EECS 282']});
db.courses.insert({'department': 'EECS ', 'coursenumber': '388' , 'prerequisites': ['Introduction to Computer Security','EECS 281']});
db.courses.insert({'department': 'EECS ', 'coursenumber': '427' , 'prerequisites': ['VLSI Design I','EECS 270','EECS 312','EECS 320']});
db.courses.insert({'department': 'EECS ', 'coursenumber': '441' , 'prerequisites': ['Mobile App Development for Entrepreneurs','EECS 281','EECS 370','|','EECS 373','EECS 381','EECS 388','EECS 427','EECS 442','EECS 445','EECS 467','EECS 470','EECS 475','EECS 477','EECS 478','EECS 482','EECS 483','EECS 484','EECS 485','EECS 486','EECS 487','EECS 489','EECS 490','EECS 492','EECS 493']});
db.courses.insert({'department': 'EECS ', 'coursenumber': '442' , 'prerequisites': ['Computer Vision','EECS 281']});
db.courses.insert({'department': 'EECS ', 'coursenumber': '445' , 'prerequisites': ['Introduction to Machine Learning','EECS 281']});
db.courses.insert({'department': 'EECS ', 'coursenumber': '467' , 'prerequisites': ['Autonomous Robotics','EECS 281']});
db.courses.insert({'department': 'EECS ', 'coursenumber': '470' , 'prerequisites': ['Computer Architecture','EECS 270','EECS 370']});
db.courses.insert({'department': 'EECS ', 'coursenumber': '475' , 'prerequisites': ['Introduction to Cryptography','EECS 280','EECS 376','|','EECS 203','MATH 312','MATH 412']});
db.courses.insert({'department': 'EECS ', 'coursenumber': '477' , 'prerequisites': ['Introduction to Algorithms','EECS 281','EECS 376']});
db.courses.insert({'department': 'EECS ', 'coursenumber': '481' , 'prerequisites': ['Software Engineering','EECS 281']});
db.courses.insert({'department': 'EECS ', 'coursenumber': '482' , 'prerequisites': ['Introduction to Operating Systems','EECS 281','EECS 370']});
db.courses.insert({'department': 'EECS ', 'coursenumber': '483' , 'prerequisites': ['Compiler Construction','EECS 281']});
db.courses.insert({'department': 'EECS ', 'coursenumber': '484' , 'prerequisites': ['Database Management Systems','EECS 281']});
db.courses.insert({'department': 'EECS ', 'coursenumber': '485' , 'prerequisites': ['Web Database and Information Systems','|','EECS 281','EECS 382']});
db.courses.insert({'department': 'EECS ', 'coursenumber': '486' , 'prerequisites': ['Information Retrieval and Web Search','EECS 281']});
db.courses.insert({'department': 'EECS ', 'coursenumber': '487' , 'prerequisites': ['Interactive Computer Graphics','EECS 281']});
db.courses.insert({'department': 'EECS ', 'coursenumber': '489' , 'prerequisites': ['Computer Networks','EECS 482']});
db.courses.insert({'department': 'EECS ', 'coursenumber': '490' , 'prerequisites': ['Programming Languages','EECS 281']});
db.courses.insert({'department': 'EECS ', 'coursenumber': '492' , 'prerequisites': ['Introduction to Artificial Intelligence','EECS 281']});
db.courses.insert({'department': 'EECS ', 'coursenumber': '493' , 'prerequisites': ['User Interface Development','EECS 281']});
db.courses.insert({'department': 'EECS ', 'coursenumber': '494' , 'prerequisites': ['Computer Game Design and Development','EECS 281']});
