CREATE TABLE COURSEPREREQUISITES(COURSE VARCHAR(30), PREREQUISITES VARCHAR(1000),
STATUS VARCHAR(20));

CREATE TABLE USER(FIRSTNAME VARCHAR(10), LASTNAME VARCHAR (20), EMAIL VARCHAR(20),PASSWORD
VARCHAR(20));